apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
      - cluster: kubernetes-admin-2@kubernetes
        url: https://172.31.17.230:6443
  template:
    metadata:
      name: '{{cluster}}-my-nginx-application-from-appset'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/gmvinodh-dev/argocd-manifests.git
        targetRevision: HEAD
        path: deployment-for-appset
      destination:
        server: "{{cluster}}"
        namespace: myappset

      syncPolicy:
        syncOptions:
          - CreateNamespace=true

        # automated:
        #   selfHeal: true
        #   prune: true
