apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-appset
spec:
  generators:
    - list:
      elements:
        - cluster: in-cluster
          url: https://kubernetes.default.svc
      # - cluster: kubernetes-admin-2@kubernetes
      # url: https://kubernetes.default.svc
  template:
    metadata:
      name: my-nginx-application-from-appset
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/gmvinodh-dev/argocd-manifests.git
        targetRevision: HEAD
        path: deployment-for-appset
      destination:
        server: "{{url}}"
        namespace: myappset

      syncPolicy:
        syncOptions:
          - CreateNamespace=true

        # automated:
        #   selfHeal: true
        #   prune: true
