apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-appset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-appset
  template:
    metadata:
      labels:
        app: nginx-appset
    spec:
      containers:
      - name: nginx
        image: nginx:1.18
        ports:
        - containerPort: 80
